spring:
  application:
    name: service-provider
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      percentage: 0.1

server:
  port: 6001


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
    healthcheck:
      enabled: true
      ####pom actuator###
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
