spring:
  application:
    name: eureka-feign-service
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      enabled: true
      sampler:
        percentage: 0.1   #0-1
server:
  port: 3001



eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/


logging:
  file: ${spring.application.name}.log


feign:
  hystrix:
    enabled: true

