spring:
  application:
    name: eureka-feign-service

server:
  port: 3001


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/


logging:
  file: ${spring.application.name}.log


feign:
  hystrix:
    enabled: true

spring:
 zipkin:
  base-url: http://localhost:9001