eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

server:
  port: 4001

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-feign-consumer
    api-b:
      path: /api-b/**
      serviceId: eureka-feign-service
    api-c:
      path: /api-c/**
      serviceId: eureka-ribbon-consumer
    host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeout-in-milliseconds: 60000





