spring:
  application:
    name: eureka-ribbon-consumer

server:
  port: 3003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

logging:
  file: ${spring.application.name}.log